[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.5.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
debug = false
panic = "abort"
overflow-checks = false
strip = true
